apiVersion: apps/v1
kind: Deployment
metadata:
  name: chatbot-server
spec:
  replicas: 1
  selector:
    matchLabels:
      app: chatbot
  template:
    metadata:
      labels:
        app: chatbot
    spec:
      containers:
        - name: chatbot-server-container-1
          image: gita_bot
          ports:
            - containerPort: 80

